// GENERATED by scripts/gen-image-ratios.mjs — do not edit by hand.
// Run `node scripts/gen-image-ratios.mjs` (or any build) to refresh.
//
// The real pixel size of every product capture, read from the files themselves.
// Frames use `ratio` so a capture fits exactly: no empty bars, no cropping, and
// no layout shift while the image loads.

export type ImageSize = { ratio: number; width: number; height: number };

export const IMAGE_SIZES: Record<string, ImageSize> = {
  "/products/akuntuntas.webp": { ratio: 1.6, width: 1440, height: 900 },
  "/products/amara.webp": { ratio: 1.6, width: 1600, height: 1000 },
  "/products/lumawall.webp": { ratio: 1.89, width: 1580, height: 836 },
  "/products/mosaic-akun-coa.webp": { ratio: 1.7493, width: 1200, height: 686 },
  "/products/mosaic-akun-ledger.webp": { ratio: 1.7493, width: 1200, height: 686 },
  "/products/mosaic-akun-partners.webp": { ratio: 1.7493, width: 1200, height: 686 },
  "/products/mosaic-amara-chat.webp": { ratio: 1.7493, width: 1200, height: 686 },
  "/products/mosaic-lumawall-catalog.webp": { ratio: 1.7493, width: 1200, height: 686 },
  "/products/mosaic-lumawall-library.webp": { ratio: 1.7493, width: 1200, height: 686 },
  "/products/mosaic-lumawall-performance.webp": { ratio: 1.7493, width: 1200, height: 686 },
  "/products/mosaic-nexshop-marketplace.webp": { ratio: 1.7493, width: 1200, height: 686 },
  "/products/mosaic-saybot-inbox.webp": { ratio: 1.7493, width: 1200, height: 686 },
  "/products/nexshop.webp": { ratio: 1.6, width: 1600, height: 1000 },
  "/products/saybot.webp": { ratio: 1.6, width: 1600, height: 1000 },
  "/products/tile-akuntuntas-2.webp": { ratio: 1.6, width: 1200, height: 750 },
  "/products/tile-akuntuntas-3.webp": { ratio: 1.6, width: 1200, height: 750 },
  "/products/tile-akuntuntas-4.webp": { ratio: 1.6, width: 1200, height: 750 },
  "/products/tile-lumawall-catalog.webp": { ratio: 1.89, width: 1580, height: 836 },
  "/products/tile-lumawall-displays.webp": { ratio: 1.89, width: 1580, height: 836 },
  "/products/tile-lumawall-library.webp": { ratio: 1.891, width: 1562, height: 826 },
  "/products/tile-lumawall-overview.webp": { ratio: 1.6667, width: 1500, height: 900 },
  "/products/tile-lumawall-performance.webp": { ratio: 1.89, width: 1580, height: 836 },
  "/products/tile-nexshop-berita.webp": { ratio: 1.6, width: 1200, height: 750 },
  "/products/tile-nexshop-marketplace.webp": { ratio: 1.6, width: 1200, height: 750 },
  "/products/tile-nexshop-reseller.webp": { ratio: 1.6, width: 1200, height: 750 },
  "/products/tile-saybot-2.webp": { ratio: 1.6, width: 1200, height: 750 },
  "/products/tile-saybot-3.webp": { ratio: 1.6, width: 1200, height: 750 },
  "/products/tile-saybot-4.webp": { ratio: 1.6, width: 1200, height: 750 },
};

/** Size of a capture, or undefined if it is not a known product image. */
export function imageSize(src: string): ImageSize | undefined {
  return IMAGE_SIZES[src];
}

/** Frame ratio for a capture, falling back to 16:10 for unknown images. */
export function frameRatio(src: string): number {
  return IMAGE_SIZES[src]?.ratio ?? 16 / 10;
}
