import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { ProjectDetailView } from "@/components/projects/project-detail-view";
import {
  PRODUCTS,
  PROJECT_DETAILS,
  getProduct,
  getProjectDetail,
} from "@/lib/content";

/**
 * /projects/<id> — one page per shipped product.
 *
 * Statically generated for every known id, and `dynamicParams = false` means an
 * unknown id 404s instead of rendering an empty shell. Metadata is generated per
 * product so each page has its own title, description, canonical and OG image.
 */
export const dynamicParams = false;

const SITE_URL = "https://xinet.id";

export function generateStaticParams() {
  return PRODUCTS.map((p) => ({ id: p.id }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const product = getProduct(id);
  const detail = getProjectDetail(id);
  if (!product || !detail) return {};

  const title = `${product.name} · ${detail.tagline.en}`;
  const description = `${detail.tagline.en} ${detail.problem.en}`.slice(0, 300);
  const url = `${SITE_URL}/projects/${product.id}`;
  // The per-product card generated by ./opengraph-image.tsx. Stated explicitly
  // so the image is guaranteed to be the product's own, rather than whatever
  // Next's file-convention fallback picks up from an ancestor segment.
  const ogImage = `${url}/opengraph-image`;

  return {
    title,
    description,
    alternates: { canonical: url },
    keywords: [
      product.name,
      `${product.name} Xinet`,
      product.category.en,
      product.category.id,
      "Xinet",
      "xinet.id",
      "Indonesia",
    ],
    openGraph: {
      type: "article",
      url,
      title,
      description,
      siteName: "Xinet",
      locale: "id_ID",
      alternateLocale: ["en_US"],
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: `${product.name} by Xinet. ${detail.tagline.en}`,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [ogImage],
    },
  };
}

/**
 * Structured data for one product.
 *
 * A `SoftwareApplication` node tied to the Organization, plus a `BreadcrumbList`
 * matching the breadcrumb the page actually renders (Xinet / Products / name).
 * The breadcrumb is what lets a search result show the trail instead of a bare
 * URL, and the application node is what makes the product itself resolvable.
 */
function structuredData(id: string) {
  const product = getProduct(id);
  const detail = getProjectDetail(id);
  if (!product || !detail) return null;

  const url = `${SITE_URL}/projects/${product.id}`;

  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "SoftwareApplication",
        "@id": `${url}/#software`,
        name: product.name,
        applicationCategory:
          product.category.en === "Business Tools"
            ? "FinanceApplication"
            : "BusinessApplication",
        description: product.description.en,
        url,
        screenshot: `${SITE_URL}${product.shot}`,
        operatingSystem: "Web",
        inLanguage: ["id-ID", "en-US"],
        publisher: { "@id": `${SITE_URL}/#organization` },
        ...(product.url ? { sameAs: [product.url] } : {}),
      },
      {
        "@type": "BreadcrumbList",
        "@id": `${url}/#breadcrumb`,
        itemListElement: [
          {
            "@type": "ListItem",
            position: 1,
            name: "Xinet",
            item: SITE_URL,
          },
          {
            "@type": "ListItem",
            position: 2,
            name: "Products",
            item: `${SITE_URL}/#products`,
          },
          {
            "@type": "ListItem",
            position: 3,
            name: product.name,
            item: url,
          },
        ],
      },
    ],
  };
}

export default async function ProjectPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const product = getProduct(id);
  const detail = getProjectDetail(id);

  // Unknown id, or a product with no detail written yet.
  if (!product || !detail) notFound();

  // The next product in the list, wrapping around, so every page links onward.
  const idx = PROJECT_DETAILS.findIndex((p) => p.id === id);
  const nextDetail = PROJECT_DETAILS[(idx + 1) % PROJECT_DETAILS.length];
  const nextProduct = getProduct(nextDetail.id) ?? null;
  const jsonLd = structuredData(id);

  return (
    <>
      {jsonLd && (
        <script
          type="application/ld+json"
          // The payload is built from our own constants, not user input.
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      )}
      <Navbar />
      <main id="main">
        <ProjectDetailView
          product={product}
          detail={detail}
          nextProduct={nextProduct}
          nextDetail={nextDetail}
        />
      </main>
      <Footer />
    </>
  );
}
